# Numpy Exercise for AI 240  - 10459          

#Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
#import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

#data = np.array([1,2,3,4,5])

#print(data)

#print(len(data))

print(type(data))

print(data.shape)

### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

#Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

### Save and submit your notebook in your Github account.

In [5]:
!pip install Numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [6]:
import numpy as np

In [7]:
data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


In [12]:
arr = np.array([10,20,30,40,50])
print(arr)
print(arr[0])

[10 20 30 40 50]
10


In [14]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr)


[[10 20 30]
 [40 50 60]]


In [15]:
print(arr[0])

[10 20 30]


In [16]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [17]:
arr = np.array([40,30,20,10,50])
print(np.sort(arr))

[10 20 30 40 50]


In [19]:
arr = np.array(['kiwi', 'berry','pear'])
print(np.sort(arr))

['berry' 'kiwi' 'pear']


In [22]:
#Find the indexes where the value is 9:
arr = np.array([3, 2, 14, 9, 10, 12])
indexes = np.where(arr == 9)
print(indexes)

(array([3]),)


In [23]:
### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
result = np.concatenate((arr1,arr2))
print(result)


[ 9  5  8 55 89 76]
